main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import error

handler500 = error

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quizes.urls', namespace='quizes')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizes/urls.py
from django.urls import path
from .views import *

app_name = 'quizes'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>/', quiz_view, name='quiz-view'),
    path('<pk>/save', save_quiz_view, name='save-view'),
    path('<pk>/data/', quiz_data_view, name='quiz-data-view'),
    
]

questions/models.py
from django.db import models
from quizes.models import Quiz

# Create your models here.
class Question(models.Model):
    text = models.CharField(max_length=200)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.text)

    def get_answers(self):
        # there is a foreign key to the question
        return self.answer_set.all()    

class Answer(models.Model):
    text = models.CharField(max_length=200)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'question: {self.question.text}, answer: {self.text}, correct: {self.correct}'

quizes/models.py
from django.db import models
import random

# Create your models here.

DIFFICULTY_CHOICES = (
    ('easy', 'easy'),
    ('medium', 'medium'),
    ('hard', 'hard'),
)

class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text='duration of the quiz in minutes')
    required_score_to_pass = models.IntegerField(help_text='required score in %')
    difficulty = models.CharField(max_length=6, choices=DIFFICULTY_CHOICES)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.name}-{self.topic}'

    def get_questions(self):
        # return a randomized list of questions so that it's length == the quiz's specified number of questions
        questions = list(self.question_set.all())
        random.shuffle(questions)
        return questions[:self.number_of_questions]

    class Meta:
        verbose_name_plural = 'Quizes'

results/models.py
from django.db import models
from quizes.models import Quiz
from django.contrib.auth.models import User

# Create your models here.
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.FloatField()

    def __str__(self) -> str:
        return str(self.pk)

main/views.py
from django.shortcuts import render

def error(request, exception=None):
    return render(request, 'error.html')

questions/views.py
from django.shortcuts import render

# Create your views here.

quizes/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from questions.models import Question, Answer
from results.models import Result


class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
    quizObj = Quiz.objects.get(pk=pk)
    quiz = []
    # get all questions of the specific quiz
    for q in quizObj.get_questions():
        answers = []
        # for each question get all answers
        for a in q.get_answers():
            # append the answer text to a temp list
            answers.append(a.text)
        # add each question with relevant answers as a key-value pairs
        quiz.append({str(q): answers})
    return JsonResponse({
        'data': quiz,
        'time': quizObj.time,
    })

def save_quiz_view(request, pk):
    if request.POST:
        # get the data and convert it from QueryDict to python dict
        data = dict(request.POST)
        data.pop('csrfmiddlewaretoken')
        
        quiz = Quiz.objects.get(pk=pk)
        user = request.user

        # get questions objects
        questions = [Question.objects.get(text=k) for k in data.keys()]
        # get selected answers
        selected_answers = [a[0] for a in data.values()]

        results = []
        score = 0
        for i, question in enumerate(questions):
            correct_answer = Answer.objects.get(question=question, correct=True).text
            selected_answer = selected_answers[i]
            if selected_answer == correct_answer:
                score += 1
            results.append(
                {str(question): 
                    {   'correct_answer': correct_answer, 
                        'selected_answer': selected_answer if selected_answer != '' else 'not answered'
                    }
                }
            )

        score *= (100 / quiz.number_of_questions)
        Result.objects.create(quiz=quiz, user=user, score=score)
        print(score)

        required_score = quiz.required_score_to_pass

        if score >= required_score:
            return JsonResponse({'passed': True, 'score': score, 'results': results})

        return JsonResponse({'passed': False, 'score': score, 'results': results})

results/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!-- custom css & js-->
    <link rel="stylesheet" href={% static 'css/style.css' %}>

    {% block scripts %}
    {% endblock scripts %}

    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</body>

</html>

templates/error.html
{% extends 'base.html' %}

{% block title %}Error{% endblock title %}

{% comment %} <link rel="stylesheet" href="style.css"> {% endcomment %}
{% block content %}
    <div class="error-page">
        <h1>Oops, something went wrong!</h1>
        <p>We're sorry, but an error has occurred. Please try again later.</p>
    </div>
{% endblock content %}

templates/quizes/main.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
Home
{% endblock title %}

{% block content %}

    <!-- Modal -->
    <div class="modal fade" id="quizStartModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you ready to start?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modal-body-confirm"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">no</button>
                    <button type="button" id="start-button" class="btn btn-success">yes</button>
                </div>
            </div>
        </div>
    </div>

    <div class='h1'>Quiz List</div>
    <hr>
    {% for obj in  object_list%}
        <button
            class="btn btn-link modal-button"
            data-pk="{{obj.pk}}"
            data-quiz="{{obj.name}}"
            data-questions="{{obj.number_of_questions}}"
            data-difficulty="{{obj.difficulty}}"
            data-time="{{obj.time}}"
            data-pass="{{obj.required_score_to_pass}}"
            data-toggle="modal"
            data-target="#quizStartModal">
            {{obj.name}}
        </button>
        <br>
    {% endfor %}

{% endblock content %}

templates/quizes/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
    {{obj.name}}
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col">
            <strong style="font-size: 23px;">{{obj.name}}</strong>
            <p>Score to pass: {{obj.required_score_to_pass}}%</p>
        </div>
        <div class="col text-center" id="timer-box" style="font-size: 23px;font-weight: bold;"></div>
        <div class="col text-right">
            <a href="{% url 'quizes:main-view' %}" class="btn btn-danger">Exit</a>
        </div>
    </div>
    
    <form id="quiz-form" class="mt-3 mb-3">
        {% csrf_token %}
        <div id="quiz-box"></div>
        <button type="sumbit" class="btn btn-primary mt-3">Save</button>
    </form>

<div id="score-box"></div>
<div id="result-box"></div>

{% endblock content %}